name: Hello World!
on:
  push:
    branches:
      - main
jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: Now it is
        run: |
          echo Today is $(date)
      - name: Print Name
        run: |
          echo "My name is faizal"

  
